### ISSUE TITLE
Limit text and remove unnecessary media present without blog

### ISSUE THREAD

**Issue by sarthakhanda** [KartikAnand2804/blogchain#2]
![image](https://user-images.githubusercontent.com/71185918/121037762-58fb0100-c7cd-11eb-88ee-6afe28e377c3.png)

**Comment by KartikAnand2804** [comment]
limited text

**Comment by KartikAnand2804** [comment]
![Screenshot (701)](https://user-images.githubusercontent.com/84150500/121136463-4fb47780-c853-11eb-82ee-cadc7c97e4da.png)
